### PR TITLE
Fix ped

### LINKED ISSUE #162: [PE-D][Tester D] Missing space in the error message for status command
After providing an invalid status, the error message is missing a space in "matchonly"

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: gyulong1/ped#4

### PR DESCRIPTION
**Pull request by KevinEyo1**
Closes #162 #168 #171 #180

### CODE REVIEW

File: src/main/java/seedu/ultron/model/opening/Keydate.java [hunk 1]
```diff
@@ -44,11 +47,19 @@ public static boolean isValidKeydate(String[] test) {
         if (test.length != 2 || test[0] == null || test[1] == null) {
             return false;
         }
+        if (test[0].strip().isEmpty()) {
+            return false;
+        }
         try {
             LocalDate.parse(test[1], dateFormat);
```
Comment (Lanreath) [inline src/main/java/seedu/ultron/model/opening/Keydate.java:54]: Parsing is done twice here

File: src/main/java/seedu/ultron/model/opening/Keydate.java [hunk 2]
```diff
@@ -15,11 +18,11 @@ public class Keydate implements Comparable<Keydate> {
     public static final String MESSAGE_CONSTRAINTS = "Keydates should be of the format key@date "
             + "and adhere to the following constraints:\n"
             + "1. The key should only contain alphabetic characters and must not be blank or made of only whitespace.\n"
-            + "2. This is followed by a '@' and then a date. The date should only be in the format yyyy-MM-dd.\n"
+            + "2. This is followed by a '@' and then a date. The date should only be in the format YYYY-MM-DD.\n"
             + "eg. CodingAssignment@2023-01-01\n";
     private static final String DATE_ERROR = "Date should be valid.";
     private static final DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
```
Comment (Lanreath) [inline src/main/java/seedu/ultron/model/opening/Keydate.java:24]: Modify the static formatter instead of creating a new instance every parse

**Review by Lanreath — CHANGES_REQUESTED** [review]
Minor changes to be made

File: src/main/java/seedu/ultron/model/opening/Keydate.java [hunk 3]
```diff
@@ -15,11 +18,12 @@ public class Keydate implements Comparable<Keydate> {
...
```
Comment (Lanreath) [inline src/main/java/seedu/ultron/model/opening/Keydate.java:24]: Remove formatter

File: src/main/java/seedu/ultron/model/opening/Keydate.java [hunk 4]
```diff
@@ -3,6 +3,9 @@
 import static java.util.Objects.requireNonNull;
 import static seedu.ultron.commons.util.AppUtil.checkArgument;
 
+import java.text.DateFormat;
+import java.text.ParseException;
+import java.text.SimpleDateFormat;
 import java.time.LocalDate;
 import java.time.format.DateTimeFormatter;
```
Comment (Lanreath) [inline src/main/java/seedu/ultron/model/opening/Keydate.java:10]: Remove ununsed imports

**Review by Lanreath — CHANGES_REQUESTED** [review]
Some extra lines to be deleted

**Review by Lanreath — APPROVED** [review]
LGTM
